### ISSUE TITLE
Redhat : zabbix.agent creates a directory "*.conf"

### ISSUE THREAD

**Issue by jschaeff** [saltstack-formulas/zabbix-formula#111]
When applying zabbix.agent on redhat, the minion creates a directory `/etc/zabbix/zabbix-agend.d/*.conf`.

This comes from https://github.com/saltstack-formulas/zabbix-formula/blob/master/zabbix/map.jinja#L77
Removing this line solves the problem.

**Comment by hatifnatt** [comment]
Fixed via #145
