### ISSUE TITLE
Add support for windows zabbix agent.

### ISSUE THREAD

**Issue by absmith82** [saltstack-formulas/zabbix-formula#112]
While zabbix servers and proxies are only available from packages on linux machines.  The agent is compiled for all kinds of OS's.  Since windows is usually a large component in organizations, I think it would be nice to have an official state for installing and configuring a windows zabbix agent.  The agent would have to be downloaded from zabbix website, or alternatively an installer in winrepo/-ng for zabbix agent (which also does not exist).  The configuration is the same, however would need to have a file path default changed for windows.

**Comment by absmith82** [comment]
I have created pull request #113 to deal with this issue.

**Comment by absmith82** [comment]
Just wondering if there is any movement on checking my pull request to make sure that it can be merged.  Thanks

**Comment by myii** [comment]
Fixed by #113.
