### ISSUE TITLE
Conflicting ID 'apt-transport-https'

### ISSUE THREAD

**Issue by xenadmin** [saltstack-formulas/zabbix-formula#122]
PR #114 and #120 introduced a problem, which I should have tested better, I'm sorry. 
It seems like the comments in `repo.sls` already mention it, but the link is dead. Haven't seen this. I will create a PR to fix it in #120 .

```
    Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'apt-transport-https' and is found in SLS 'base:zabbix.proxy.repo' and SLS 'base:zabbix.agent.repo'
ERROR: Minions returned with non-zero exit code
```

**Comment by OrangeDog** [comment]
Using unprefixed IDs in formulae is a bad idea.
It also conflicts with elasticsearch-formula (who also shoudn't've done this).

**Comment by aboe76** [comment]
@OrangeDog nice find, I'm sorry I didn't catch that.

**Comment by xenadmin** [comment]
Solved.
