### ISSUE TITLE
Warning on zabbix-frontend_debconf

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack-formulas/zabbix-formula#14]
When running this state on 2015.5 I receive the following:

```
    Warnings: '__prerequired__' is an invalid keyword argument for
              'debconf.set'. If you were trying to pass additional data to be
              used in a template context, please populate 'context' with 'key:
              value' pairs. Your approach will work until Salt Carbon is out.
              Please update your state files.
```

**Comment by TaiSHiNet** [comment]
It does the same on zabbix-server_debconf

**Comment by moreda** [comment]
I'll take a look at it ASAP. Thanks for reporting.

**Comment by mchugh19** [comment]
Can this be closed? I don't see the referenced error.

**Comment by pauldalewilliams** [comment]
@mchugh19 A little late but can you still verify this isn't an issue?  I haven't tested this formula on Debian personally but I can if needed.

**Comment by mchugh19** [comment]
I'm not sure either. We run zabbix on centos at the moment. I'd say close out the issue, and if it reoccurs, we can open a new one.

**Comment by hatifnatt** [comment]
I'll close this due old age.
