### ISSUE TITLE
Unify repos

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack-formulas/zabbix-formula#15]
Why not unify repos? Currently (for some strange reason) zabbix.agent and zabbix.server are not setting the repo, although zabbix.frontend is!
Tried to follow your link to an issue but it 404'd on me

**Comment by pauldalewilliams** [comment]
Based on the current state of this formula, I believe this issue can be closed.  Any objections?

**Comment by TaiSHiNet** [comment]
None, haven't used the formula in a while tho, but I'm guessing people will reopen if this were to be an issue again
