### ISSUE TITLE
Do not enable 'APT::Install-Recommends "false";' unconditionally

### ISSUE THREAD

**Issue by olfway** [saltstack-formulas/zabbix-formula#19]
I understand why it was added, but i'm sure it's a bad thing to enable it unconditionally for whole system

Also it's possible now to use "--without-recommends" flag just for a package
According to docs https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html

----
Whether to install the packages marked as recommended. Default is True. Currently only works with APT-based systems.
New in version 2015.5.0.
httpd:
  pkg.installed:
    - install_recommends: False

**Comment by babilen** [comment]
I totally agree and would consider the behaviour of this formula to be quite buggy in this regard. Could you please test the PR mentioned above and check if it resolves this issue?

**Comment by babilen** [comment]
@olfway Does the PR above resolve your issue?

**Comment by olfway** [comment]
@babilen yep, this fixes it, thanks!

**Comment by babilen** [comment]
Great! I'll wait for the PR to be merged before closing this bug.
