### ISSUE TITLE
New gpg key required for Ubuntu Xenial (16.04)

### ISSUE THREAD

**Issue by syphernl** [saltstack-formulas/zabbix-formula#32]
Zabbix has finally released packages for Ubuntu Xenial (16.04). However, it appears they are not using the signing key listed in the repo but key `082AB56BA14FE591` instead which is available on the (ubuntu) keyserver.

If this key is missing, the Zabbix packages cannot be installed.

**Comment by tomduijf** [comment]
Created PR which includes this: #38
