### ISSUE TITLE
debconf need a single package name

### ISSUE THREAD

**Issue by landergate** [saltstack-formulas/zabbix-formula#35]
Merging #27 broke debconf configuration in two places:
- zabbix.server.conf https://github.com/saltstack-formulas/zabbix-formula/blob/master/zabbix/server/conf.sls#L28
- zabbix.frontend.conf https://github.com/saltstack-formulas/zabbix-formula/blob/master/zabbix/frontend/conf.sls#L33

More info in discussion: https://github.com/saltstack-formulas/zabbix-formula/commit/19ed5413564e9f4c6fb4ab5b5031304dd56a7927#commitcomment-18739220

Founded by @aboe76

**Comment by peterloron** [comment]
Which packages do we need to call debconf on? Just the zabbix-server-mysql? Maybe loop through packages and run the debconf step only if we match that name?

**Comment by mchugh19** [comment]
Whoops. Just sent over pull #44 for this same issue. @peterloron Yep, should just be zabbix-server-mysql. The debconf step preseeds the mysql bits, so that's all that is necessary.

**Comment by hatifnatt** [comment]
I'm agree this can be closed. Currently names are hardcoded but I think it's acceptable solution in this case.
