### ISSUE TITLE
Recommendation for zabbix pid file

### ISSUE THREAD

**Issue by mchugh19** [saltstack-formulas/zabbix-formula#42]
It looks like the formula requires a definition for zabbix-agent:pidfile. Otherwise, the generated zabbix conf file will point to 'false' and be invalid. This is fine expect that rhel7 uses /run, while rhel 6 uses /var/run. What is the recommended method of handling this split? Couldn't these defaults be included in the existing map files, rather than forcing OS policy into pillars?

**Comment by aboe76** [comment]
see pr #41

**Comment by mchugh19** [comment]
This gets slightly stickier in that redhat 6 uses /var/run/zabbix/whatever.pid where redhat 7 uses /run/zabbix/whatever.pid. These paths are also important and can't just be changed willy nilly since the systemd unit file uses the same names. 

There is some discussion about this in the zabbix bug tracker here: https://support.zabbix.com/browse/ZBX-9867

This would be easier if the service was adjusted to not double fork and could just use a simpler unit file. But for now I think the two options are for the salt formula can be adjusted to do the right thing on the appropriate OS, or it can do a standard thing everywhere and also modify the unit file.

**Comment by scottking2** [comment]
@mchugh19 Did you ever figure out what the best course of action is to get this to work with RHEL 6 and 7?

**Comment by mchugh19** [comment]
Looks like we had to modify the agent and server files to lookup the pid file from the jinja map. The line:
`{% if settings.get('pidfile', false) %}PidFile={{ settings.get('pidfile') }}{% endif %}`
should be something more like:
`PidFile={{ salt['config.get']('zabbix-agent:pidfile', zabbix.agent.pidfile) }}`

**Comment by dharif23** [comment]
I am using zabbix formula on Ubuntu 16.04.02 and the `zabbix.agent.conf` state can't restart the agent service. I have tried the above `pidfile` source code but still, it can't restart the service. On the other hand, I have tried this `pidfile` reference in a custom `.jinja` file (that is basically a working agent configuration file for zabbix agent) it works fine. I think there is something else broken. I would appreciate any suggestion.

**Comment by chrisbier** [comment]
I have also noticed this issue in Ubuntu 16.04. The PID file gets set to `/tmp/zabbix_agentd.pid` (Which is the default for the zabbix agent) instead of the `map.jinja` setting of  `/var/run/zabbix/zabbix_agentd.pid`. I'll see if I can figure out why.

**Comment by chrisbier** [comment]
Ah! The jinja config file reads the pillars, and the example pillar doesn't have the pidfile mentioned.

**Comment by pauldalewilliams** [comment]
Is this still an issue @chrisbier and @mchugh19?  Looks like changes in #71 and later refinements should have fixed this problem.

**Comment by mchugh19** [comment]
I've not tested, but the updates look good. I'll close this issue, and if there are any problems we can open a new one.
