### ISSUE TITLE
Repo version not updating.

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/zabbix-formula#48]
Hi

I'm trying to set the version of Zabbix-agent to 3.2. I've set the pillar data as follows and it is still installing the 2.2 version. Please help, what am I missing? 

> zabbix:
>   lookup:
>     agent:
>       version: 3.2
>       version_repo: 3.2

**Comment by scottking2** [comment]
@waynegemmell you need to change version_repo to be 3.2 in map.jinga. make sure to change it on all of the versions.

**Comment by waynegemmell** [comment]
Thanks
