### ISSUE TITLE
What versions of mysql,php,nginx are you using for formulas 

### ISSUE THREAD

**Issue by kydouglas** [saltstack-formulas/zabbix-formula#58]
I can load most the the sls and conf files, although I still see the following. Are you able to point me in the right direction as the latest formulas appear to be broken with zabbix top.sls example for non zabbix related sls and conf

error - https://pastebin.com/b8nYN9bT

top.sls - https://pastebin.com/n274eJzw

formulas - https://pastebin.com/anY8aZ6F

**Comment by dharif23** [comment]
Please check that the formula is in your `file_roots` under `base` environment in the salt master file. 
```Shell
file_roots:
  base:
    - /srv/formulas/mysql-formula
```
This might help.

**Comment by pauldalewilliams** [comment]
Closing as this issue is old and not directly related to the formula.  I plan to update the readme and pillar.example after some pending changes and will share a working set of configs that's more accurate than what's listed on the current readme.
