### ISSUE TITLE
formula maintained?

### ISSUE THREAD

**Issue by mchugh19** [saltstack-formulas/zabbix-formula#67]
Is this formula still being maintained? There are many issues and pull requests that have been outstanding for months.

**Comment by aboe76** [comment]
@mchugh19 reviewing pull request and commenting on them if you tested them will help with maintaining this, because not everyone is using zabbix...

**Comment by whiteinge** [comment]
Yeah, we'd love any help here, @mchugh19. Feel free to dive in and review & merge any PRs that you see fit. 👍

**Comment by mchugh19** [comment]
Could someone provide feedback on #55 and #56. Those are my PRs so I would like an outside opinion.

**Comment by aboe76** [comment]
@mchugh19 I have added some assignees to review the PR's

**Comment by mchugh19** [comment]
Hey all. Could we poll the mailing list for maintainers? There's a few PRs stacking up, which seem to have gotten okay reviews. We likely just need a group to be able to hit the merge button.

**Comment by pauldalewilliams** [comment]
I'm trying to help maintain this formula now.  Are you OK if we close this issue @mchugh19?  I think you'll see more activity over the next month, and I'm about to clean up some of the stale issues that are no longer relevant.

**Comment by mchugh19** [comment]
Great! Thanks!
