### ISSUE TITLE
E: Unable to locate package zabbix-sender

### ISSUE THREAD

**Issue by Gabri-connect** [saltstack-formulas/zabbix-formula#94]
im running ubuntu 16
Doing a salt '*' state.apply
Function: pkg.installed

Fails with: E: Unable to locate package zabbix-sender

**Comment by Gabri-connect** [comment]
What is zabbix-sender anyway, cant locate the package

**Comment by Gabri-connect** [comment]
I found this: https://github.com/hengyunabc/zabbix-sender
Looks dodgy

**Comment by xenadmin** [comment]
This is the official description: https://www.zabbix.com/documentation/3.4/manual/concepts/sender
This is the installation guide with official sources: https://www.zabbix.com/documentation/3.4/manual/installation/install_from_packages/debian_ubuntu
This is the Ubuntu repo: http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/

**Comment by Gabri-connect** [comment]
Found the problem:

In Ubuntu Trusty:
https://packages.ubuntu.com/trusty/amd64/zabbix-agent/filelist
-- Contains zabbix-sender

In Ubuntu Bionic:
https://packages.ubuntu.com/bionic/amd64/zabbix-agent/filelist
-- Zabbix-sender was removed

**Comment by xenadmin** [comment]
I personally would always recommend to use the official Zabbix SIA repo over the distro packages. I say that as someone who uses Zabbix exclusively with Debian 
repo.zabbix.com

**Comment by hatifnatt** [comment]
I know I'm really late, but you can simply override list of packages to install. You don't have `zabbix-sender` package? Alright get rid of it, create pillar like below and apply where necessary.
```yaml
zabbix:
  lookup:
    agent:
      pkgs:
        - zabbix-agent
```

**Comment by hatifnatt** [comment]
There is two suggested solutions and no reaction from original author. I suppose the problem is solved in some way.
