### ISSUE TITLE
Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'mysql'

### ISSUE THREAD

**Issue by syphernl** [saltstack-formulas/zabbix-formula#99]
Running this formula on a clean Ubuntu 18.04 results in an error:
```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:zabbix.mysql.schema' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'mysql'
```

This appears to be due to [this](https://github.com/saltstack-formulas/zabbix-formula/blob/master/zabbix/mysql/schema.sls#L36) check.

**Comment by syphernl** [comment]
Seems like a local issue since `python-mysqldb` was missing for some reason.

**Comment by timwsuqld** [comment]
@syphernl I believe this is still a bug. The python-mysqldb package is installed by the zabbix.mysql.conf state. The zabbix.mysql.schema state should detect that the zabbix.mysql.conf state hasn't yet run and given us python-mysqldb, before it tries to use salt.mysql which caused the whole jinja compile to fail.

I should be able to include all required states, apply it, and it should work. Currently I need to remove zabbix.mysql.schema, apply zabbix.mysql.conf, and then add zabbix.mysql.schema back in.

**Comment by q1x** [comment]
I concur, running into this issue as well.

**Comment by ghormoon** [comment]
I've run into simmilar issue with psql: Rendering SLS 'production:zabbix.pgsql.schema' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'postgres'

seems it's an issue if you have zabbix.pgsql.schema and run it against clean VM that doesn't have postgresql (client) installed.
it should be installed by zabbix.pgsql.conf (which is dependency of zabbix.pgsql.schema), but it won't run at all, therefore not install it ...
